### ISSUE TITLE
/etc/startup1.d/01-gem-depends: line 142: /dev/tty: No such device or address

### ISSUE THREAD

**Issue by cmoulliard** [jekyll/docker-jekyll#19]
When I execute the docker cmd to start the container, I get this error using boot2docker

```
docker run --rm --label=jekyll --label=stable --volume=$(pwd):/srv/jekyll -p 127.0.0.1:4000:4000 jekyll/stable jekyll s
/etc/startup1.d/01-gem-depends: line 142: /dev/tty: No such device or address
```

**Comment by envygeeks** [comment]
Hmmm.... that seems like an edge case that shouldn't be happening.  Can you please do the following so I can get some information:

```
docker run -it envygeeks/ubuntu ls -la /dev
```

and give me the output.

**Comment by cmoulliard** [comment]
Here is the output : 

```
docker run -it envygeeks/ubuntu ls -la /dev
Unable to find image 'envygeeks/ubuntu:latest' locally
latest: Pulling from envygeeks/ubuntu
018582e0582e: Pull complete
dd24cc186bdb: Pull complete
cd32d1869b41: Pull complete
2e36cdbc3388: Pull complete
5d327f3c0b84: Pull complete
2b1c32ff9ab5: Pull complete
3cd1e0c6b628: Already exists
cab7c4dcf81b: Already exists
602e15acbcda: Already exists
020431a88ee9: Already exists
6be21d1e5d1e: Already exists
Digest: sha256:10160007329b7ea48c23ef82cd0f73076e8a0295988cf1cb27c975152f7584a8
Status: Downloaded newer image for envygeeks/ubuntu:latest
Starting services.
total 4
drwxr-xr-x  5 root root      380 Jun 29 17:06 .
drwxr-xr-x 41 root root     4096 Jun 29 17:06 ..
crw-------  1 root root 136,   0 Jun 29 17:06 console
lrwxrwxrwx  1 root root       13 Jun 29 17:06 fd -> /proc/self/fd
crw-rw-rw-  1 root root   1,   7 Jun 29 17:06 full
c---------  1 root root  10, 229 Jun 29 17:06 fuse
lrwxrwxrwx  1 root root       11 Jun 29 17:06 kcore -> /proc/kcore
drwxrwxrwt  2 root root       40 Jun 29 17:06 mqueue
crw-rw-rw-  1 root root   1,   3 Jun 29 17:06 null
lrwxrwxrwx  1 root root        8 Jun 29 17:06 ptmx -> pts/ptmx
drwxr-xr-x  2 root root        0 Jun 29 17:06 pts
crw-rw-rw-  1 root root   1,   8 Jun 29 17:06 random
drwxrwxrwt  2 root root       40 Jun 29 17:06 shm
lrwxrwxrwx  1 root root       15 Jun 29 17:06 stderr -> /proc/self/fd/2
lrwxrwxrwx  1 root root       15 Jun 29 17:06 stdin -> /proc/self/fd/0
lrwxrwxrwx  1 root root       15 Jun 29 17:06 stdout -> /proc/self/fd/1
crw-rw-rw-  1 root root   5,   0 Jun 29 17:06 tty
crw-rw-rw-  1 root root   1,   9 Jun 29 17:06 urandom
crw-rw-rw-  1 root root   1,   5 Jun 29 17:06 zero
Stopping services.
```

**Comment by envygeeks** [comment]
That's weird, you have a tty according to that output, and that's the base image of the image (envygeeks/ruby) this image uses...  Perhaps for some reason Docker doesn't feel necessary to establish a tty on Windows of which I cannot explain why but all things said, I guess I can just hit fd/1 directly through stdout and see if that resolves this problem.

**Comment by envygeeks** [comment]
@cmoulliard can you please try the image again with the new build, I started just pushing 1 back into &0 instead of pushing it directly to the TTY, hopefully this resolves your problem since technically in a round-about way 1 points to &0 before we silence it.

**Comment by cmoulliard** [comment]
I get a new error now : 

```
Status: Downloaded newer image for jekyll/stable:latest
Starting services.
diff: Gemfile.old.06292015: No such file or directory
/etc/startup1.d/01-gem-depends: line 86: echo: write error: Bad file descriptor
```

**Comment by envygeeks** [comment]
Okay, apparently this is gonna have to wait till tonight when I can get on one of my Windows boxes because boot2docker has some serious caveats I gotta work around, can you please tell me your Windows version so I can jump on a box with that version on it?

Thanks.

**Comment by cmoulliard** [comment]
I'm using macosx & boot2docker `Boot2Docker-cli version: v1.6.2`, docker `1.6.2`

**Comment by envygeeks** [comment]
That's weird, we just tested it on OS X with Boot2Docker and don't get that error at all on the current image, can you try updating your Docker and see if it still happens?

**Comment by cmoulliard** [comment]
Upgraded boot2docker & docker too (> 1.7) but this problem is still there : 

```
Status: Downloaded newer image for jekyll/stable:latest
Starting services.
diff: Gemfile.old.06302015: No such file or directory
/etc/startup1.d/01-gem-depends: line 86: echo: write error: Bad file descriptor

docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```

**Comment by jimnanney** [comment]
This is the output from what @envygeeks and I did.

Mac OS X Yosemite, Latest Docker and Boot2Docker

Output as follows:

bash
Last login: Wed Jul  1 16:25:02 on ttys006

unset DYLD_LIBRARY_PATH ; unset LD_LIBRARY_PATH
mkdir -p ~/.boot2docker
if [ ! -f ~/.boot2docker/boot2docker.iso ]; then cp /usr/local/share/boot2docker/boot2docker.iso ~/.boot2docker/ ; fi
/usr/local/bin/boot2docker init 
/usr/local/bin/boot2docker up 
$(/usr/local/bin/boot2docker shellinit)
docker version
[2.2.2] ➜  ~  bash
bash-3.2$ unset DYLD_LIBRARY_PATH ; unset LD_LIBRARY_PATH
bash-3.2$ mkdir -p ~/.boot2docker
bash-3.2$ if [ ! -f ~/.boot2docker/boot2docker.iso ]; then cp /usr/local/share/boot2docker/boot2docker.iso ~/.boot2docker/ ; fi
bash-3.2$ /usr/local/bin/boot2docker init 
bash-3.2$ /usr/local/bin/boot2docker up 
Waiting for VM and Docker daemon to start...
.........................oooooooooooooooooo
Started.
Writing /Users/jimnanney/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/jimnanney/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/jimnanney/.boot2docker/certs/boot2docker-vm/key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_HOST=tcp://192.168.59.104:2376
    export DOCKER_CERT_PATH=/Users/jimnanney/.boot2docker/certs/boot2docker-vm
    export DOCKER_TLS_VERIFY=1

bash-3.2$ $(/usr/local/bin/boot2docker shellinit)
Writing /Users/jimnanney/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Users/jimnanney/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Users/jimnanney/.boot2docker/certs/boot2docker-vm/key.pem
bash-3.2$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
bash-3.2$ git clone https://github.com/jekyll/jekyll
fatal: destination path 'jekyll' already exists and is not an empty directory.
bash-3.2$ rm -rf jekyll
bash-3.2$ git clone https://github.com/jekyll/jekyll
Cloning into 'jekyll'...
remote: Counting objects: 30538, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 30538 (delta 5), reused 0 (delta 0), pack-reused 30521
Receiving objects: 100% (30538/30538), 9.49 MiB | 3.34 MiB/s, done.
Resolving deltas: 100% (17848/17848), done.
Checking connectivity... done.
bash-3.2$ cd jekyll/site
bash-3.2$ docker run -it jekyll/stable
Unable to find image 'jekyll/stable:latest' locally
latest: Pulling from jekyll/stable
cab7c4dcf81b: Pulling fs layer 
602e15acbcda: Pulling fs layer 
020431a88ee9: Pull complete 
6be21d1e5d1e: Pull complete 
ae29f94ac463: Pull complete 
348ff54081f4: Pull complete 
63689ee1e074: Pull complete 
3245414b6fac: Pull complete 
cde8031466f1: Pull complete 
e92b51faeac8: Pull complete 
5e88cf0f3e7b: Pull complete 
987b545514e4: Pull complete 
56afa2930447: Pull complete 
7eab00105cf1: Pull complete 
4cabc6f9f6c7: Pull complete 
33f28294ed4d: Pull complete 
9d58c67f3fc5: Pull complete 
f4dc7702a41c: Pull complete 
8b7b014fadde: Pull complete 
5cdbfcde3874: Pull complete 
6867edccdc70: Pull complete 
abc8727ba88e: Pull complete 
3dd6bd61b598: Pull complete 
8ea6bfc5ce76: Pull complete 
d548d8cf0bec: Already exists 
Digest: sha256:8a6d9ec98e69cec415266afff8d34f26a8ccaa43d676fe698d7cb08232e528a1
Status: Downloaded newer image for jekyll/stable:latest
Starting services.
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '/srv/jekyll'
Configuration file: /srv/jekyll/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.

**Comment by cmoulliard** [comment]
The problem occurs when we mount the volume between the host machine and boot2docker

Works
```
docker run -it jekyll/stable
Starting services.
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
      Generating...
                    done.
 Auto-regeneration: enabled for '/srv/jekyll'
Configuration file: /srv/jekyll/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```
Issue
```
docker run --rm --volume=/Users/chmoulli/MyProjects/MyConferences/cmoulliard.github.com:/srv/jekyll jekyll/stable
Starting services.
diff: Gemfile.old.07022015: No such file or directory
/etc/startup1.d/01-gem-depends: line 94: echo: write error: Bad file descriptor
```

**Comment by aculich** [comment]
A fix was suggested here: https://github.com/envygeeks/docker-ubuntu/issues/1

**Comment by envygeeks** [comment]
I'm fixing this now, I didn't see that ticket. For some reason Github didn't subscribe me to my own repo so I didn't see that ticket.
