### ISSUE TITLE
An error occurred while installing ffi (1.9.8), and Bundler cannot continue

### ISSUE THREAD

**Issue by everett-toews** [jekyll/docker-jekyll#23]
Trying to run jekyll/stable

    $ docker run --rm --label=jekyll --label=stable --volume=$(pwd):/srv/jekyll -t -p 4000:4000 jekyll/stable jekyll s

    Starting services.
    Ign http://mirrors.ocf.berkeley.edu/ubuntu/ vivid InRelease
    Ign http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-updates InRelease
    Ign http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-security InRelease
    Get:1 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid Release.gpg [933 B]
    Get:2 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-updates Release.gpg [933 B]
    Get:3 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-security Release.gpg [933 B]
    Get:4 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid Release [217 kB]
    Get:5 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-updates Release [63.5 kB]
    Get:6 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-security Release [63.5 kB]
    Get:7 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid/main amd64 Packages [1,766 kB]
    Get:8 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid/restricted amd64 Packages [22.8 kB]
    Get:9 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid/universe amd64 Packages [8,393 kB]
    Get:10 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-updates/main amd64 Packages [198 kB]
    Get:11 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-updates/restricted amd64 Packages [40 B]
    Get:12 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-updates/universe amd64 Packages [107 kB]
    Get:13 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-security/main amd64 Packages [112 kB]
    Get:14 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-security/restricted amd64 Packages [40 B]
    Get:15 http://mirrors.ocf.berkeley.edu/ubuntu/ vivid-security/universe amd64 Packages [52.6 kB]
    Fetched 11.0 MB in 4s (2,499 kB/s)
    Reading package lists... Done
    cat: .apt: No such file or directory
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Fetching gem metadata from https://rubygems.org/..........
    Fetching version metadata from https://rubygems.org/...
    Fetching dependency metadata from https://rubygems.org/..
    Using RedCloth 4.2.9
    Using i18n 0.7.0
    Using json 1.8.3
    Using minitest 5.7.0
    Using thread_safe 0.3.5
    Using tzinfo 1.2.2
    Installing activesupport 4.2.2
    Using blankslate 2.1.2.4
    Using hitimes 1.2.2
    Using timers 4.0.1
    Using celluloid 0.16.0
    Using fast-stemmer 1.0.2
    Using classifier-reborn 2.0.3
    Using coffee-script-source 1.9.1.1
    Using execjs 2.5.2
    Using coffee-script 2.4.1
    Using colorator 0.1
    Installing ffi 1.9.8 with native extensions

    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby -r ./siteconf20150724-37-geht40.rb extconf.rb
    checking for ffi.h... *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
    	--with-opt-dir
    	--without-opt-dir
    	--with-opt-include
    	--without-opt-include=${opt-dir}/include
    	--with-opt-lib
    	--without-opt-lib=${opt-dir}/lib
    	--with-make-prog
    	--without-make-prog
    	--srcdir=.
    	--curdir
    	--ruby=/usr/bin/$(RUBY_BASE_NAME)
    	--with-ffi_c-dir
    	--without-ffi_c-dir
    	--with-ffi_c-include
    	--without-ffi_c-include=${ffi_c-dir}/include
    	--with-ffi_c-lib
    	--without-ffi_c-lib=${ffi_c-dir}/lib
    	--with-libffi-config
    	--without-libffi-config
    	--with-pkg-config
    	--without-pkg-config
    /usr/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
    	from /usr/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:321:in `open'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:321:in `open'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
    	from /usr/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
    	from extconf.rb:16:in `<main>'

    extconf failed, exit code 1

    Gem files will remain installed in /tmp/bundler20150724-37-ohabulffi-1.9.8/gems/ffi-1.9.8 for inspection.
    Results logged to /tmp/bundler20150724-37-ohabulffi-1.9.8/extensions/x86_64-linux/2.2.0/ffi-1.9.8/gem_make.out
    An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
    Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.
    There was an unrecoverable error, bye.

Versions:

    Mac OS X 10.9.5

    $ boot2docker version
    Boot2Docker-cli version: v1.7.0
    Git commit: 7d89508
    
    $ docker version
    Client version: 1.7.0
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): 0baf609
    OS/Arch (client): darwin/amd64
    Server version: 1.7.0
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): 0baf609
    OS/Arch (server): linux/amd64

Am I missing something?

**Comment by envygeeks** [comment]
Yes, for now if you wish to use bundler with our image you must supply a `.apt` file with the dependencies required to compile all the gems you will need (this will change in the future when I supply at least the base dependencies for most.)

Add a `.apt` file into your Jekyll root (make sure to ignore it so that it doesn't end up in _site) with the following and you should be good to go:

```
libxml2-dev
libxslt1-dev
libreadline6-dev
build-essential
zlib1g-dev
```

**Comment by everett-toews** [comment]
:+1:

**Comment by envygeeks** [comment]
As a site note, you might want to also cache that bundle install into vendor/bundle with `-e BUNDLE_CACHE=true`, this will speed up later boots with the image (because we don't cache your bundle installs by default.)
