### ISSUE TITLE
Gem native dependenices

### ISSUE THREAD

**Issue by MhSaadany** [jekyll/docker-jekyll#27]
I have 'jekyll-assets' in my Gemfile which apparently requires the 'mini_magick' gem.
mini_magick needs the ImageMagick or GraphicsMagick command-line tool to be installed.

When running the container I get:
```
Moving Gemfile to Gemfile.docker because jekyll is not included.
Configuration file: /srv/jekyll/_config.yml
jekyll 2.5.3 | Error:  ImageMagick/GraphicsMagick is not installed
```
Do you think there can be a way to deal with those native dependencies other than building a custom image?

**Comment by envygeeks** [comment]
There is already a way to deal with that (unless you are using jekyll/pages -- then we restrict what you can do so you are forced to work in their environment.)  Find the packages you need on https://pkgs.alpinelinux.org and add one package at time to a `.apk` file in your Jekyll root and it will install those.

**Comment by envygeeks** [comment]
Oh I see what's going on here.  It doesn't compile those so we never trigger that.

**Comment by envygeeks** [comment]
You can now do as I stated above and send --env='FORCE_APK_INSTALL=true' and it will always install whatever is in your '.apk' file for you.
